image: guss77/dind-awscli:latest
services:
  - docker:dind

stages:
#  - build
#  - release
  - deploy

variables:
  DOCKER_BUILDKIT: 1
  AWS_REGION: eu-central-1
  APLICATION_NAME: api

before_script:
# Login to the docker registry
  - docker info
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY


# build_image:
#   stage: build
#   script:
#     # Build the docker image and use the latest release as a docker cache source
#     # https://testdriven.io/blog/faster-ci-builds-with-docker-cache/
#     - docker pull $CI_REGISTRY_IMAGE:latest || true
#     - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# release_latest:
#   stage: release
#   only:
#     - master
#   script:
#     - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
#     - docker push $CI_REGISTRY_IMAGE:latest

deploy_moon:
  stage: deploy
  environment: moon
  when: manual
  script:
    - export SERVICE_NAME="api-moon"
    - export DOCKER_IMAGE="nginx:latest"
    - ./deploy-srcipts/deploy.sh
